server:
  port: 8080
  tomcat:
    relaxed-query-chars: ["{", "}", "[", "]"]

spring:
  application:
    name: tasks_organizer

management:
  server:
    port: ${server.port}

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"